# Generated by Django 5.2.5 on 2025-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('weightlifting', 'Weightlifting'), ('yoga', 'Yoga'), ('walking', 'Walking'), ('hiking', 'Hiking'), ('other', 'Other')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('calories', models.IntegerField()),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
